// This file is autogenerated by scraper.ts
  import Dwarf_Scroll_IImg from "./img/Dwarf_Scroll_I.png";
import Dwarf_Scroll_IIImg from "./img/Dwarf_Scroll_II.png";
import Dwarf_Scroll_IIIImg from "./img/Dwarf_Scroll_III.png";
import Dwarf_Scroll_IVImg from "./img/Dwarf_Scroll_IV.png";
import Chipped_AmphoraImg from "./img/Chipped_Amphora.png";
import ArrowheadImg from "./img/Arrowhead.png";
import Ancient_DollImg from "./img/Ancient_Doll.png";
import Elvish_JewelryImg from "./img/Elvish_Jewelry.png";
import Chewing_StickImg from "./img/Chewing_Stick.png";
import Ornamental_FanImg from "./img/Ornamental_Fan.png";
import Dinosaur_EggImg from "./img/Dinosaur_Egg.png";
import Rare_DiscImg from "./img/Rare_Disc.png";
import Ancient_SwordImg from "./img/Ancient_Sword.png";
import Rusty_SpoonImg from "./img/Rusty_Spoon.png";
import Rusty_SpurImg from "./img/Rusty_Spur.png";
import Rusty_CogImg from "./img/Rusty_Cog.png";
import Chicken_StatueImg from "./img/Chicken_Statue.png";
import Ancient_SeedImg from "./img/Ancient_Seed.png";
import Prehistoric_ToolImg from "./img/Prehistoric_Tool.png";
import Dried_StarfishImg from "./img/Dried_Starfish.png";
import AnchorImg from "./img/Anchor.png";
import Glass_ShardsImg from "./img/Glass_Shards.png";
import Bone_FluteImg from "./img/Bone_Flute.png";
import Prehistoric_HandaxeImg from "./img/Prehistoric_Handaxe.png";
import Dwarvish_HelmImg from "./img/Dwarvish_Helm.png";
import Dwarf_GadgetImg from "./img/Dwarf_Gadget.png";
import Ancient_DrumImg from "./img/Ancient_Drum.png";
import Golden_MaskImg from "./img/Golden_Mask.png";
import Golden_RelicImg from "./img/Golden_Relic.png";
import Strange_Doll_greenImg from "./img/Strange_Doll_(green).png";
import Strange_Doll_yellowImg from "./img/Strange_Doll_(yellow).png";
import Prehistoric_ScapulaImg from "./img/Prehistoric_Scapula.png";
import Prehistoric_TibiaImg from "./img/Prehistoric_Tibia.png";
import Prehistoric_SkullImg from "./img/Prehistoric_Skull.png";
import Skeletal_HandImg from "./img/Skeletal_Hand.png";
import Prehistoric_RibImg from "./img/Prehistoric_Rib.png";
import Prehistoric_VertebraImg from "./img/Prehistoric_Vertebra.png";
import Skeletal_TailImg from "./img/Skeletal_Tail.png";
import Nautilus_FossilImg from "./img/Nautilus_Fossil.png";
import Amphibian_FossilImg from "./img/Amphibian_Fossil.png";
import Palm_FossilImg from "./img/Palm_Fossil.png";
import TrilobiteImg from "./img/Trilobite.png";
  export const Artefacts = [
    {Name: "Dwarf Scroll I", Image: Dwarf_Scroll_IImg, Sources: [["Tilling in Mines/Skull Cavern","(any floor) (0.16%)"],["Several monsters","(0.5% each)"]]}
  ,{Name: "Dwarf Scroll II", Image: Dwarf_Scroll_IIImg, Sources: [["Tilling in Mines","(floor 1-40) (0.1%)"],["Ghost drop","(0.5%)"],["Frost Bat drop","(0.5%)"],["Dust Sprite drop","(0.5%)"],["Blue Slime drop","(0.5%)"]]}
  ,{Name: "Dwarf Scroll III", Image: Dwarf_Scroll_IIIImg, Sources: [["Several monsters drop","(1.5% for Blue Slime, 0.5% for others)"]]}
  ,{Name: "Dwarf Scroll IV", Image: Dwarf_Scroll_IVImg, Sources: [["Any Monster","(other than Iridium Bat, Iridium Crab, and [[Haunted Skull]]) (0.1%)"],["Tilling in Mines","(floor 80+) (0.2%)<section end=\"dwarfscrolls\" />"]]}
  ,{Name: "Chipped Amphora", Image: Chipped_AmphoraImg, Sources: [["Town","(3%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Arrowhead", Image: ArrowheadImg, Sources: [["Mountain","(1.6%)"],["Forest","(1.6%)"],["Bus Stop","(1.6%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Ancient Doll", Image: Ancient_DollImg, Sources: [["Mountain","(3%)"],["Forest","(2.4%)"],["Bus Stop","(2.4%)"],["Town","(0.8%)"],["Fishing Chest","(0.8-0.9%)"],["Feast of the Winter St","r"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Elvish Jewelry", Image: Elvish_JewelryImg, Sources: [["Forest","(0.8%)"],["Fishing Chest","(0.8-0.9%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Chewing Stick", Image: Chewing_StickImg, Sources: [["Mountain","(1.5%)"],["Forest","(1.5%)"],["Town","(0.8%)"],["Fishing Chest","(0.8-0.9%)"],["Duggy drop","(2%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Ornamental Fan", Image: Ornamental_FanImg, Sources: [["Beach","(1.6%)"],["Forest","(0.7%)"],["Town","(0.6%)"],["Fishing Chest","(0.8-0.9%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Dinosaur Egg", Image: Dinosaur_EggImg, Sources: [["Mountain","(0.6%)"],["Fishing Chest","(0.8-0.9%)"],["Foraged on prehistoric floors of the Skull Cave","n"],["Pepper Rex drop","(10%)"]]}
  ,{Name: "Rare Disc", Image: Rare_DiscImg, Sources: [["Fishing Chest","(0.8-0.9%)"],["Bats drop","(except Iridium Bat) (0.1%)"],["Shadow Brute, [[Shadow Shaman]], [[Spider]] drop","(0.3%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Ancient Sword", Image: Ancient_SwordImg, Sources: [["Forest","(0.7%)"],["Mountain","(0.6%)"],["Fishing Chest","(0.8-0.9%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Rusty Spoon", Image: Rusty_SpoonImg, Sources: [["Town","(4% + 6-11%)"],["Fishing Chest","(0.8-0.9%)"],["Tilling in Mines/Skull Cavern","(any floor) (0.16%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Rusty Spur", Image: Rusty_SpurImg, Sources: [["Farm","(10%)"],["Tilling in Mines/Skull Cavern","(any floor) (0.16%)"],["Fishing Chest","(0.8-0.9%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Rusty Cog", Image: Rusty_CogImg, Sources: [["Mountain","(4%)"],["Tilling in Mines/Skull Cavern","(any floor) (0.16%)"],["Fishing Chest","(0.8-0.9%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Chicken Statue", Image: Chicken_StatueImg, Sources: [["Farm","(9%)"],["Fishing Chest","(0.8-0.9%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Ancient Seed", Image: Ancient_SeedImg, Sources: [["Forest","(0.7%)"],["Mountain","(0.7%)"],["Fishing Chest","(0.8-0.9%)"],["Monster drop","(Bug, [[Cave Fly]], [[Grub]], [[Mutant Fly]], [[Mutant Grub]]: 0.5%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Prehistoric Tool", Image: Prehistoric_ToolImg, Sources: [["Bus Stop","(3%)"],["Forest","(2.1%)"],["Mountain","(2%)"],["Fishing Chest","(0.8-0.9%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Dried Starfish", Image: Dried_StarfishImg, Sources: [["Beach","(8%)"],["Fishing Chest","(0.8-0.9%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Anchor", Image: AnchorImg, Sources: [["Beach","(4%)"],["Fishing Chest","(0.8-0.9%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Glass Shards", Image: Glass_ShardsImg, Sources: [["Beach","(7%)"],["Fishing Chest","(0.8-0.9%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Bone Flute", Image: Bone_FluteImg, Sources: [["Forest","(0.7%)"],["Mountain","(0.7%)"],["Town","(0.4%)"],["Fishing Chest","(0.8-0.9%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Prehistoric Handaxe", Image: Prehistoric_HandaxeImg, Sources: [["Bus Stop","(4%)"],["Mountain","(3%)"],["Forest","(3%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Dwarvish Helm", Image: Dwarvish_HelmImg, Sources: [["Tilling in Mines","(floor 1-40) (0.1%)"],["Geode","(3%)"],["Omni Geode","(1%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Dwarf Gadget", Image: Dwarf_GadgetImg, Sources: [["Tilling in Mines","(floor 41-80) (0.1%)"],["Magma Geode","(4%)"],["Omni Geode","(1%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Ancient Drum", Image: Ancient_DrumImg, Sources: [["Bus Stop","(0.7%)"],["Forest","(0.7%)"],["Town","(0.4%)"],["Frozen Geode","(3%)"],["Omni Geode","(1%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Golden Mask", Image: Golden_MaskImg, Sources: [["Desert","(3%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Golden Relic", Image: Golden_RelicImg, Sources: [["Desert","(6%)"],["Artifact Trove","(3.7%)"]]}
  ,{Name: "Strange Doll (green)", Image: Strange_Doll_greenImg, Sources: [["Farm","(0.08%)"],["Bus Stop","(0.07%)"],["Town","(0.07%)"],["Forest","(0.06%)"],["Mountain","(0.06%)"],["Beach","(0.06%)"],["Tilling in Mines/Skull Cavern","(any floor) (0.03%)"],["Fishing Chest","(≈0.14%)"],["Secret Note #","7"]]}
  ,{Name: "Strange Doll (yellow)", Image: Strange_Doll_yellowImg, Sources: [["Farm","(0.08%)"],["Bus Stop","(0.07%)"],["Town","(0.07%)"],["Forest","(0.06%)"],["Mountain","(0.06%)"],["Beach","(0.06%)"],["Tilling in Mines/Skull Cavern","(any floor) (0.03%)"],["Fishing Chest","(≈0.14%)"],["Secret Note #","8"]]}
  ,{Name: "Prehistoric Scapula", Image: Prehistoric_ScapulaImg, Sources: [["Forest","(3-6%)"],["Town","(0.7%)"],["Skeleton drop","(0.5%)"],["Bone Nodes","(0.8%)"]]}
  ,{Name: "Prehistoric Tibia", Image: Prehistoric_TibiaImg, Sources: [["Railroad","(4-8%)"],["Forest","(0.6%)"],["Pepper Rex drop","(30%)"],["Bone Nodes","(0.8%)"]]}
  ,{Name: "Prehistoric Skull", Image: Prehistoric_SkullImg, Sources: [["Mountain","(0.6% + 3-6%)"],["Haunted Skull drop","(1.3%)"],["Bone Nodes","(0.8%)"]]}
  ,{Name: "Skeletal Hand", Image: Skeletal_HandImg, Sources: [["Backwoods","(4-8%)"],["Beach","(0.6%)"],["Haunted Skull drop","(1.3%)"],["Bone Nodes","(0.8%)"]]}
  ,{Name: "Prehistoric Rib", Image: Prehistoric_RibImg, Sources: [["Town","(2.2-4%)"],["Farm","(0.8%)"],["Pepper Rex drop","(30%)"],["Bone Nodes","(0.8%)"]]}
  ,{Name: "Prehistoric Vertebra", Image: Prehistoric_VertebraImg, Sources: [["Bus Stop","(0.7% + 3-5%)"],["Pepper Rex drop","(30%)"],["Bone Nodes","(0.8%)"]]}
  ,{Name: "Skeletal Tail", Image: Skeletal_TailImg, Sources: [["Tilling in Mines/Skull Cavern","(any floor)"],["Fishing Chest","(3.1-3.4%)"],["Bone Nodes","(0.8%)"]]}
  ,{Name: "Nautilus Fossil", Image: Nautilus_FossilImg, Sources: [["Beach","(1.8%)"],["Fishing Chest","(3.1-3.4%)"],["Bone Nodes","(0.8%)"]]}
  ,{Name: "Amphibian Fossil", Image: Amphibian_FossilImg, Sources: [["Forest","(0.6%)"],["Mountain","(0.6%)"],["Fishing Chest","(3.1-3.4%)"],["Bone Nodes","(0.8%)"]]}
  ,{Name: "Palm Fossil", Image: Palm_FossilImg, Sources: [["Desert","(7%)"],["Forest","(0.6% + 3-5%)"],["Beach","(0.6%)"],["Bone Nodes","(0.8%)"]]}
  ,{Name: "Trilobite", Image: TrilobiteImg, Sources: [["Beach","(1.7% + 2.3-5%)"],["Forest","(1.9%)"],["Mountain","(1.8%)"],["Bone Nodes","(0.8%)"]]}
  ]